### ISSUE TITLE
cmd-arrow to jump to start/end of line

### ISSUE THREAD

**Issue by gkjpettet** [ktekinay/XsEdit#26]
Would it be possible to add the macOS keyboard shortcut of `cmd` plus either the left or right arrow key to jump to the beginning or end of the current line? `option`-left/right works to jump back/forwards a word so I was wondering if it was possible to add this other system-standard key combination?

**Comment by ktekinay** [comment]
That's part of the CustomEditField control, and I haven't looked at that code. But that might be a good place for you to start.

**Comment by gkjpettet** [comment]
Will do. Thanks.
